trigger:
  branches:
    include:
      - userr_branch

pool:
  name: Default

steps:
  # Étape 1 : Vérification de Java (facultatif)
  - script: |
      java -version
    displayName: 'Vérification de la version Java'

  # Étape 2 : Exécution des tests avec Maven
  - task: Maven@3
    inputs:
      mavenPomFile: 'pom.xml'
      goals: 'clean test'
      mavenVersionOption: 'Path'
      mavenPath: '/opt/maven'
      javaHomeOption: 'Path'
      jdkUserInputPath: '/usr/lib/jvm/java-17-openjdk-amd64'
      mavenOptions: '-Xmx1024m'

  # Étape 3 : Publier les résultats des tests
  - task: PublishTestResults@2
    inputs:
      testResultsFormat: 'JUnit'
      testResultsFiles: '**/surefire-reports/TEST-*.xml'

  # Étape 4 : Publier le rapport ExtentReports
  - task: PublishBuildArtifacts@1
    inputs:
      artifactName: 'ExtentReports'
      targetPath: '$(System.DefaultWorkingDirectory)/target' # Dossier où se trouve ExtentReports.html
      pathToPublish: '$(System.DefaultWorkingDirectory)/target/ExtentReports.html' # Fichier à publier
