trigger:
  branches:
    include:
      - userr_branch # Assure-toi que c'est bien le nom exact de ta branche

pool:
  name: Default # Vérifie que ton agent est bien enregistré dans ce pool

steps:
  # Étape 1 : Vérifier Java (optionnel)
  - script: |
      java -version
    displayName: 'Vérification de la version Java'

  # Étape 2 : Télécharger le code source
  - checkout: self
    displayName: 'Téléchargement du code source'

  # Étape 3 : Lancer Maven
  - task: Maven@4
    inputs:
      mavenPomFile: 'pom.xml' # Assure-toi que ce fichier est bien présent à la racine de ton dépôt
      goals: 'clean test'
      javaHomeOption: 'Path' # Utilise la version Java installée sur ton agent
      mavenOptions: '-Xmx1024m'
      mavenVersionOption: 'Default'
    displayName: 'Exécution des tests avec Maven'

  # Étape 4 : Publier les résultats des tests
  - task: PublishTestResults@2
    inputs:
      testResultsFormat: 'JUnit'
      testResultsFiles: '**/surefire-reports/TEST-*.xml'
      failTaskOnFailedTests: true
    displayName: 'Publication des résultats de tests'
