trigger:
  branches:
    include:
      - userr_branch # Ta branche de code

pool:
  name: Default # Pool de ton agent (Default si configuré comme tel)

steps:
  # Étape 1 : Vérifier Java (facultatif)
  - script: |
      java -version
    displayName: 'Vérification de la version Java'

  # Étape 2 : Lancer Maven
  - task: Maven@3
    inputs:
      mavenPomFile: 'pom.xml' # Chemin vers ton fichier pom.xml
      goals: 'clean test'
      mavenVersionOption: 'Path' # Spécifie qu'on utilise un chemin personnalisé
      mavenPath: '/opt/maven/bin/mvn' # Chemin vers la version de Maven installée
      javaHomeOption: 'Path'
      jdkUserInputPath: '/usr/lib/jvm/java-17-openjdk-amd64' # Chemin vers JDK 17
      mavenOptions: '-Xmx1024m'



  # Étape 3 : Publier les résultats des tests
  - task: PublishTestResults@2
    inputs:
      testResultsFormat: 'JUnit'
      testResultsFiles: '**/surefire-reports/TEST-*.xml'
      failTaskOnFailedTests: true
